site_name: Debezium Server Bigquery Consumer
site_url: http://memiiso.github.io/debezium-server-bigquery
repo_url: https://github.com/memiiso/debezium-server-bigquery
theme:
  name: material
  features:
    #    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    #    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.tabs.link
nav:
  - Home: index.md
  - bigquerybatch: bigquerybatch.md
  - bigquerystream: bigquerystream.md
  - Configuration: configuration.md
  #  - Migration Guideline: migration.md
  #  - FAQ: faq.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.snippets:
      base_path: [ !relative $config_dir ]
      check_paths: true