name: deploy-mkdocs-documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - docs
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-documentation.yml'

concurrency:
  group: mkdocs-deploy
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install --upgrade pip mkdocs-material
      - run: mkdocs gh-deploy --force