name: CI to Github Container Registry

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Main
    if: github.repository_owner == 'memiiso'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        name: Build & push Docker image
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/debezium-server-bigquery:latest

#      - uses: vlaurin/action-ghcr-prune@main
#        name: Prune Untagged Container Images
#        with:
#          token: ${{ secrets.PAT }}
#          organization: ${{ github.repository_owner }}
#          container: debezium-server-bigquery
#          dry-run: true # Dry-run first, then change to `false`
#          untagged: true